name: 'Jira Changelog'
description: 'Generates a changelog message by looking at Jira issue keys ([DEV-123]) in commit messages.'
inputs:
    jira_host:
        description: 'Root host of your JIRA installation without protocol. // (i.e "yourapp.atlassian.net")'
        default: 'https://atlassian.net'
        required: true
    jira_email:
        description: 'Email address of the user to login with'
        default: 'e@email.com'
        required: true
    jira_token:
        description: 'Auth token of the user to login with'
        default: 'knmD98cbfsd£jnfjnH?KHKH'
        required: true
    jira_base_url:
        description: 'Jira base web URL for changelog message entries'
        default: 'https://atlassian.net'
        required: false
    jira_ticket_id_pattern:
        description: 'Regex used to match the issue ticket key'
        default: /\[([a-z]+[0-9]?\-[0-9]+)\]/i
        required: false
    source_control_range_from:
        description: 'Starting branch to get range of commits'
        default: 'master'
        required: false
    source_control_range_to:
        description: 'Ending branch to get range of commits'
        required: true
    release_version:
        description: 'Release version to generate in Jira'
        default: ''
        required: false
    github_token:
        description: 'Github Token for retrieving PRs from repository'
        default: ''
        required: true 
    repo_name:
        description: 'Full name of the github repository'
        default: ''
        required: true 
    generate_notes_only:
        description: 'Should tickets be updated to associate the release version, or just generate updated notes?'
        default: 'false'
        required: false
outputs:
    changelog_message:
        description: 'Generated changelog entry'
    qanotes_message:
        description: 'Generated QA Notes'
runs:
    using: 'node12'
    main: 'index.js'